//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.05 at 01:14:50 PM CET
//
// Modified by adding getStates
//

package easywebflow.config;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for flowType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="flowType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="datamodel" type="{}flowData"/>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element name="state" type="{}stateType"/>
 *           &lt;element name="final" type="{}stateType"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{}stringType" />
 *       &lt;attribute name="initial" use="required" type="{}stringType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "flowType", propOrder = {
    "datamodel",
    "stateOrFinal"
})
public class FlowType {

    @XmlElement(required = true)
    protected FlowData datamodel;
    @XmlElementRefs({
        @XmlElementRef(name = "final", type = JAXBElement.class),
        @XmlElementRef(name = "state", type = JAXBElement.class)
    })
    protected List<JAXBElement<StateType>> stateOrFinal;
    @XmlAttribute(required = true)
    protected String name;
    @XmlAttribute(required = true)
    protected String initial;

    /**
     * Gets the value of the datamodel property.
     * 
     * @return
     *     possible object is
     *     {@link FlowData }
     *     
     */
    public FlowData getDatamodel() {
        return datamodel;
    }

    /**
     * Sets the value of the datamodel property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlowData }
     *     
     */
    public void setDatamodel(FlowData value) {
        this.datamodel = value;
    }

    /**
     * Gets the value of the stateOrFinal property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stateOrFinal property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStateOrFinal().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link StateType }{@code >}
     * {@link JAXBElement }{@code <}{@link StateType }{@code >}
     * 
     * 
     */
    public List<JAXBElement<StateType>> getStateOrFinal() {
        if (stateOrFinal == null) {
            stateOrFinal = new ArrayList<JAXBElement<StateType>>();
        }
        return this.stateOrFinal;
    }

    // TODO THIS IS BAAAD fix it and isFinal method in StateType
    public List<StateType> getStates(){
    	List<StateType> list = new ArrayList<StateType>();
    	for (JAXBElement<StateType> el : this.stateOrFinal){
    		StateType st = el.getValue();
    		if(el.getName().equals(ObjectFactory._FlowTypeFinal_QNAME)){
    			st.setFinalState(true);
    		}
    		list.add(st);
    	}
    	return list;
    }
    
    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the initial property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInitial() {
        return initial;
    }

    /**
     * Sets the value of the initial property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInitial(String value) {
        this.initial = value;
    }

}
