//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.05 at 01:14:50 PM CET 
//


package easywebflow.config;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the easywebflow.config package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Scxml_QNAME = new QName("", "scxml");
    public final static QName _FlowTypeFinal_QNAME = new QName("", "final");
    public final static QName _FlowTypeState_QNAME = new QName("", "state");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: easywebflow.config
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link StateData }
     * 
     */
    public StateData createStateData() {
        return new StateData();
    }

    /**
     * Create an instance of {@link FlowType }
     * 
     */
    public FlowType createFlowType() {
        return new FlowType();
    }

    /**
     * Create an instance of {@link TransitionType }
     * 
     */
    public TransitionType createTransitionType() {
        return new TransitionType();
    }

    /**
     * Create an instance of {@link InvokationType }
     * 
     */
    public InvokationType createInvokationType() {
        return new InvokationType();
    }

    /**
     * Create an instance of {@link FlowData }
     * 
     */
    public FlowData createFlowData() {
        return new FlowData();
    }

    /**
     * Create an instance of {@link StateType }
     * 
     */
    public StateType createStateType() {
        return new StateType();
    }

    /**
     * Create an instance of {@link ParamType }
     * 
     */
    public ParamType createParamType() {
        return new ParamType();
    }

    /**
     * Create an instance of {@link SecuredType }
     * 
     */
    public SecuredType createSecuredType() {
        return new SecuredType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FlowType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "scxml")
    public JAXBElement<FlowType> createScxml(FlowType value) {
        return new JAXBElement<FlowType>(_Scxml_QNAME, FlowType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StateType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "final", scope = FlowType.class)
    public JAXBElement<StateType> createFlowTypeFinal(StateType value) {
        return new JAXBElement<StateType>(_FlowTypeFinal_QNAME, StateType.class, FlowType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StateType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "state", scope = FlowType.class)
    public JAXBElement<StateType> createFlowTypeState(StateType value) {
        return new JAXBElement<StateType>(_FlowTypeState_QNAME, StateType.class, FlowType.class, value);
    }

}
