//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.10 at 02:03:57 AM CET 
//


package easywebflow.config;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for stateType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="stateType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="datamodel" type="{}stateData" minOccurs="0"/>
 *         &lt;element name="onentry" type="{}invokationList" minOccurs="0"/>
 *         &lt;element name="transition" type="{}transitionType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="onexit" type="{}invokationList" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{}stringType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "stateType", propOrder = {
    "datamodel",
    "onentry",
    "transition",
    "onexit"
})
public class StateType {

    protected StateData datamodel;
    @XmlElementWrapper(name="onentry")
    @XmlElement(name="invoke")
    protected List<InvokationType> onentry;
    protected List<TransitionType> transition;
    @XmlElementWrapper(name="onexit")
    @XmlElement(name="invoke")
    protected List<InvokationType> onexit;
    @XmlAttribute(required = true)
    protected String id;

    /**
     * Gets the value of the datamodel property.
     * 
     * @return
     *     possible object is
     *     {@link StateData }
     *     
     */
    public StateData getDatamodel() {
        return datamodel;
    }

    /**
     * Sets the value of the datamodel property.
     * 
     * @param value
     *     allowed object is
     *     {@link StateData }
     *     
     */
    public void setDatamodel(StateData value) {
        this.datamodel = value;
    }

    /**
     * Gets the value of the onentry property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the invoke property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOnentry().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InvokationType }
     * 
     * 
     */
    public List<InvokationType> getOnentry() {
        if (onentry == null) {
        	onentry = new ArrayList<InvokationType>();
        }
        return this.onentry;
    }

    /**
     * Gets the value of the transition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the transition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTransition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TransitionType }
     * 
     * 
     */
    public List<TransitionType> getTransition() {
        if (transition == null) {
            transition = new ArrayList<TransitionType>();
        }
        return this.transition;
    }

    /**
     * Gets the value of the onexit property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the invoke property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOnexit().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InvokationType }
     * 
     * 
     */
    public List<InvokationType> getOnexit() {
        if (onexit == null) {
        	onexit = new ArrayList<InvokationType>();
        }
        return this.onexit;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
