//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.10 at 02:03:57 AM CET 
//


package easywebflow.config;

import java.util.ArrayList;
import java.util.List;
import java.util.StringTokenizer;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for transitionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="transitionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="invoke" type="{}invokationType"/>
 *       &lt;/choice>
 *       &lt;attribute name="target" use="required" type="{}stringType" />
 *       &lt;attribute name="event" use="required" type="{}stringType" />
 *       &lt;attribute name="cond" type="{}stringType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "transitionType", propOrder = {
    "invoke"
})
public class TransitionType {

    protected List<InvokationType> invoke;
    @XmlAttribute(required = true)
    protected String target;
    @XmlAttribute(required = true)
    protected String event;
    @XmlTransient
    protected String cond;
    @XmlTransient
    protected String comparedObject;
    @XmlTransient
    protected String comparedValue;
    
    /**
     * Gets the value of the invoke property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the invoke property.
     * 
     * <p>
     * For example, to add a new item, do as follows:@XmlAttribute
     * <pre>
     *    getInvoke().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InvokationType }
     * 
     * 
     */
    public List<InvokationType> getInvoke() {
        if (invoke == null) {
            invoke = new ArrayList<InvokationType>();
        }
        return this.invoke;
    }

    /**
     * Gets the value of the target property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTarget() {
        return target;
    }

    /**
     * Sets the value of the target property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTarget(String value) {
        this.target = value;
    }

    /**
     * Gets the value of the event property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEvent() {
        return event;
    }

    /**
     * Sets the value of the event property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEvent(String value) {
        this.event = value;
    }

    /**
     * Gets the value of the cond property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @XmlAttribute
    public String getCond() {
        return new String(this.comparedObject+"=="+this.comparedValue);
    }

    /**
     * Sets the value of the cond property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCond(String value) {
    	this.cond = value;
    	StringTokenizer st = new StringTokenizer(value, "==");
        this.comparedObject = st.nextToken().trim();
        this.comparedValue = st.nextToken().trim();        
    }

    public String getComparedValue() {
		return comparedValue;
	}
    
    public void setComparedValue(String comparedValue) {
		this.comparedValue = comparedValue;
	}
    
    public String getComparedObject() {
		return comparedObject;
	}
    
    public void setComparedObject(String comparedObject) {
		this.comparedObject = comparedObject;
	}
}
